providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.build]
cmds = [
  "cd app && npm install && npm run build",
  "cd backend && pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "cd backend && python3 main.py"
